export { CustomLink } from './CustomLink'
export { CenteredPage } from './CenteredPage'
export { Header } from './Header/Header'
export { PrimaryButton } from './PrimaryButton/PrimaryButton'
export { Shortcut } from './Shortcut/Shortcut'
export { Gift } from './Gift/Gift'
export { Footer } from './Footer/Footer'