export { ArrowDropLeft } from './ArrowDropLeft'
export { View } from './View'
export { Chat } from './Chat'
export { Telegram } from './Telegram'
export { Insta } from './Insta'
export { Tag } from './Tag'
export { Plus } from './Plus'